# Generated by Django 4.0.4 on 2022-05-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('room', 'date'), name='uniqe_rom_reservations'),
        ),
    ]
