# Generated by Django 4.0.4 on 2022-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0002_reservation_uniqe_rom_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date']},
        ),
    ]
